/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfaz;

import clase.Cafetera;
import javax.swing.JOptionPane;

/**
 *
 * @author SERVIDOR
 */
public class Principal6 extends javax.swing.JFrame {

    /**
     * Creates new form Principal6
     */
    Cafetera cf;
    public Principal6() {
        initComponents();
   }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtCapacidad_m = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtCantidad_a = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        cmdLlenado = new javax.swing.JButton();
        cmdServirTaza = new javax.swing.JButton();
        cmdVaciar = new javax.swing.JButton();
        cmdAgregar = new javax.swing.JButton();
        cmdLimpiar = new javax.swing.JButton();
        cmdCrear = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 204, 153));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Ebrima", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 102, 51));
        jLabel1.setText("CAFETERA");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 10, -1, -1));

        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 51, 0), 4));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setText("Cantidad que desea ingresar:");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 80, -1, -1));

        jLabel3.setText("Capacidad Maxima:");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 20, -1, -1));

        txtCapacidad_m.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jPanel2.add(txtCapacidad_m, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 40, 50, 30));

        jLabel4.setText("Cantidad Actual:");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 80, -1, -1));
        jPanel2.add(txtCantidad_a, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 100, 50, 30));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 60, 280, 150));

        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 51, 0), 4));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        cmdLlenado.setText("Llenar la cafetera");
        cmdLlenado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdLlenadoActionPerformed(evt);
            }
        });
        jPanel3.add(cmdLlenado, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 50, 130, 30));

        cmdServirTaza.setText("Servir taza ");
        cmdServirTaza.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdServirTazaActionPerformed(evt);
            }
        });
        jPanel3.add(cmdServirTaza, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 90, 110, 30));

        cmdVaciar.setText("Vaciar la cafetera");
        cmdVaciar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdVaciarActionPerformed(evt);
            }
        });
        jPanel3.add(cmdVaciar, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 130, 120, 30));

        cmdAgregar.setText("Agregar Cafe");
        cmdAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdAgregarActionPerformed(evt);
            }
        });
        jPanel3.add(cmdAgregar, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 170, 100, 30));

        cmdLimpiar.setText("Limpiar");
        cmdLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdLimpiarActionPerformed(evt);
            }
        });
        jPanel3.add(cmdLimpiar, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 210, 90, 30));

        cmdCrear.setText("Crear");
        cmdCrear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdCrearActionPerformed(evt);
            }
        });
        jPanel3.add(cmdCrear, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 10, 90, 30));

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 220, 230, 270));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 509, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 20, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 501, Short.MAX_VALUE)
        );

        setSize(new java.awt.Dimension(545, 539));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void cmdLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdLimpiarActionPerformed
        txtCantidad_a.setText("");
        txtCapacidad_m.setText("");
        
        
    }//GEN-LAST:event_cmdLimpiarActionPerformed

    private void cmdCrearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdCrearActionPerformed
       int capm,cant_a;
       
       if (txtCapacidad_m.getText().trim().isEmpty()){
           JOptionPane.showMessageDialog(this, "Digite la capacidad maxima");
           txtCapacidad_m.requestFocusInWindow(); 
       }else if (txtCantidad_a.getText().trim().isEmpty()){
          JOptionPane.showMessageDialog(this, "Digite la cantidad actual");
           txtCantidad_a.requestFocusInWindow(); 
       }else if (Integer.parseInt(txtCantidad_a.getText().trim())==0){
        JOptionPane.showMessageDialog(this, "La capacidad maxima no puede ser cero");   
       }else{
        cant_a=Integer.parseInt(txtCantidad_a.getText());
        capm=Integer.parseInt(txtCapacidad_m.getText());
        if (cant_a>capm){
        JOptionPane.showMessageDialog(this, "La cantidad actual no puede ser mayor a su capacidad","Error",JOptionPane.ERROR_MESSAGE);
        txtCapacidad_m.requestFocusInWindow();
        }else{
            cf = new Cafetera (cant_a,capm);
         JOptionPane.showMessageDialog(this, "Se ha creado la cafetera exitosamente!");
        }
         
        
        
       }
       
    }//GEN-LAST:event_cmdCrearActionPerformed

    private void cmdLlenadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdLlenadoActionPerformed
       int p,cant_a,capm;
        
    p=JOptionPane.showConfirmDialog(this, "En realidad desea llenar la cafetera?","Pregunta",JOptionPane.YES_NO_OPTION);
    if (p==JOptionPane.YES_OPTION){
     cant_a=cf.getCantAc();
     cf.llenarcafetera();
    txtCantidad_a.setText(String.valueOf(cant_a));
      JOptionPane.showMessageDialog(this, "Llenado exitoso!"); 
    }else{
        
    }
        
    }//GEN-LAST:event_cmdLlenadoActionPerformed

    private void cmdServirTazaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdServirTazaActionPerformed
        int aux,cant_a,capm,cantc;
         aux=JOptionPane.showConfirmDialog(this, "En realidad desea servir la taza de cafe?","Pregunta",JOptionPane.YES_NO_OPTION);
    if (aux==JOptionPane.YES_OPTION){
      cant_a=Integer.parseInt(txtCantidad_a.getText());
      capm=Integer.parseInt(txtCapacidad_m.getText());
      cantc=Integer.parseInt (JOptionPane.showInputDialog(this,"Digite la cantidad a servir"));
         cf.servirtaza(cantc);
         JOptionPane.showMessageDialog(this, "Taza servida!");
         txtCantidad_a.setText(""+cf.getCantAc());
    }else{   
    }
    
    }//GEN-LAST:event_cmdServirTazaActionPerformed

    private void cmdVaciarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdVaciarActionPerformed
        cf.vaciarcafetera();
        txtCantidad_a.setText(""+cf.getCantAc());
        JOptionPane.showMessageDialog(this, "Se ha vaciado exitosamente la cafetera");
    }//GEN-LAST:event_cmdVaciarActionPerformed

    private void cmdAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdAgregarActionPerformed
       int aux1,cant_a,capm,cant_ag;
       
       cant_a=Integer.parseInt(txtCantidad_a.getText());
       capm=Integer.parseInt (txtCapacidad_m.getText());
       
       cant_ag=Integer.parseInt (JOptionPane.showInputDialog(this,"Digite la cantidad de cafe"));
       cf.agregarcafe(cant_ag);
       txtCantidad_a.setText(""+cf.getCantAc());
       JOptionPane.showMessageDialog(this, "Se ha agregado el cafe exitosamente!");
               
    }//GEN-LAST:event_cmdAgregarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal6.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal6.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal6.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal6.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal6().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cmdAgregar;
    private javax.swing.JButton cmdCrear;
    private javax.swing.JButton cmdLimpiar;
    private javax.swing.JButton cmdLlenado;
    private javax.swing.JButton cmdServirTaza;
    private javax.swing.JButton cmdVaciar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JTextField txtCantidad_a;
    private javax.swing.JTextField txtCapacidad_m;
    // End of variables declaration//GEN-END:variables
}
